---
title: My Jekyll Blog
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    author: Matthijs
- scope:
    path: ''
    type: pages
  values:
    layout: page
description: A personal blog built with Jekyll, published on GitHub Pages, and managed
  with Siteleaf.
author:
  name: Matthijs
  email: your@email.com
  twitter: yourusername
baseurl: "/jekyllblog-feb26"
url: https://glidergeek.github.io
markdown: kramdown
highlighter: rouge
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-sitemap
permalink: "/blog/:year/:month/:day/:title/"
exclude:
- Gemfile
- Gemfile.lock
- ".gitignore"
- README.md
- vendor/
